const baskets = [];
const mushrooms = [
  {
    id: 'mushroom1',
    name: 'Billy',
    description: 'white',
    imgUrl: 'female',
    isMagic: true,
    isPoisonous: true,
    isDeadly: true,
  },
  {
    id: 'mushroom2',
    name: 'Billy',
    description: 'white',
    imgUrl: 'female',
    isMagic: true,
    isPoisonous: true,
    isDeadly: true,
  },
  {
    id: 'mushroom3',
    name: 'Billy',
    description: 'white',
    imgUrl: 'female',
    isMagic: true,
    isPoisonous: true,
    isDeadly: true,
  },
  {
    id: 'mushroom4',
    name: 'Billy',
    description: 'white',
    imgUrl: 'female',
    isMagic: true,
    isPoisonous: true,
    isDeadly: true,
  },
  {
    id: 'mushroom5',
    name: 'Billy',
    description: 'white',
    imgUrl: 'female',
    isMagic: true,
    isPoisonous: true,
    isDeadly: true,
  },
  {
    id: 'mushroom6',
    name: 'Billy',
    description: 'white',
    imgUrl: 'female',
    isMagic: true,
    isPoisonous: true,
    isDeadly: true,
  },
  {
    id: 'mushroom7',
    name: 'Billy',
    description: 'white',
    imgUrl: 'female',
    isMagic: true,
    isPoisonous: true,
    isDeadly: true,
  },
  {
    id: 'mushroom8',
    name: 'Billy',
    description: 'white',
    imgUrl: 'female',
    isMagic: true,
    isPoisonous: true,
    isDeadly: true,
  },
  {
    id: 'mushroom9',
    name: 'Billy',
    description: 'white',
    imgUrl: 'female',
    isMagic: true,
    isPoisonous: true,
    isDeadly: true,
  },
  {
    id: 'mushroom10',
    name: 'Billy',
    description: 'white',
    imgUrl: 'female',
    isMagic: true,
    isPoisonous: true,
    isDeadly: true,
  },
  {
    id: 'mushroom11',
    name: 'Billy',
    description: 'white',
    imgUrl: 'female',
    isMagic: true,
    isPoisonous: true,
    isDeadly: true,
  },
  {
    id: 'mushroom12',
    name: 'Billy',
    description: 'white',
    imgUrl: 'female',
    isMagic: true,
    isPoisonous: true,
    isDeadly: true,
  },
  {
    id: 'mushroom13',
    name: 'Billy',
    description: 'white',
    imgUrl: 'female',
    isMagic: true,
    isPoisonous: true,
    isDeadly: true,
  },
  {
    id: 'mushroom14',
    name: 'Billy',
    description: 'white',
    imgUrl: 'female',
    isMagic: true,
    isPoisonous: true,
    isDeadly: true,
  },
  {
    id: 'mushroom15',
    name: 'Billy',
    description: 'white',
    imgUrl: 'female',
    isMagic: true,
    isPoisonous: true,
    isDeadly: true,
  },
  {
    id: 'mushroom16',
    name: 'Billy',
    description: 'white',
    imgUrl: 'female',
    isMagic: true,
    isPoisonous: true,
    isDeadly: true,
  },
  {
    id: 'mushroom17',
    name: 'Billy',
    description: 'white',
    imgUrl: 'female',
    isMagic: true,
    isPoisonous: true,
    isDeadly: true,
  },
  {
    id: 'mushroom18',
    name: 'Billy',
    description: 'white',
    imgUrl: 'female',
    isMagic: true,
    isPoisonous: true,
    isDeadly: true,
  },
  {
    id: 'mushroom19',
    name: 'Billy',
    description: 'white',
    imgUrl: 'female',
    isMagic: true,
    isPoisonous: true,
    isDeadly: true,
  },
  {
    id: 'mushroom20',
    name: 'Billy',
    description: 'white',
    imgUrl: 'female',
    isMagic: true,
    isPoisonous: true,
    isDeadly: true,
  },
];
